pipeline {

    agent { node { label 'AGENT-1' } }
    stages {
        stage('Init') {
            steps {
                  sh '''
                       terraform init
                    '''
            }
        }
        stage('plan') {
            steps {
                   sh '''
                       terraform plan
                    '''
            }
        }
      
    }
        post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when failure'
        }
    }
}
