pipeline {

    agent { node { label 'AGENT-1' } }
     options {
           ansicolor('xterm')
    }
    stages {
        stage('Init') {
            steps {
                  sh '''
                  cd 01-vpc
                  
                  pwd
                  terraform init
                    '''
            }
        }
        stage('plan') {
            steps {
                   sh '''
                     cd 01-vpc
                     ls -ltr
                     pwd
                     terraform plan
                    '''
            }
        }
      
    }
        post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when failure'
        }
    }
}
